# Server Port Configuration
server.port=8080
server.servlet.context-path=/api/v1

# MongoDB Connection
spring.data.mongodb.uri=mongodb://localhost:27017/service_booking_hub
spring.data.mongodb.auto-index-creation=true

# Logging
logging.level.root=INFO